### PR TITLE
[fix] added support for OCI repository for Helm Charts

### LINKED ISSUE #40: OCI registry as source for Helm Charts is not working
want to use helmper - the helm-chart in in gcp container registry - but the endpoint is **oci://**

```
helm -n xxx upgrade --install xx \
  oci://us-west1-docker.pkg.dev/haarchri/xxx \
  --version "1.2.3" \
  --wait
```

i get the following error: 

```
k8s_version: 1.27.9
import:
  enabled: true
charts:
- name: xxx
  version: 1.4.0
  repo:
    name: xxx
    url: https://us-west1-docker.pkg.dev/haarchri/xxx/
registries:
- name: registry
  url: 0.0.0.0:5002
  insecure: true
  plainHTTP: true
```

`is not a valid chart repository or cannot be reached: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go value of type repo.IndexFile"}`

if i try with:

```
k8s_version: 1.27.9
import:
  enabled: true
charts:
- name: xxx
  version: 1.4.0
  repo:
    name: xxx
    url: oci://us-west1-docker.pkg.dev/haarchri/xxx/
registries:
- name: registry
  url: 0.0.0.0:5002
  insecure: true
  plainHTTP: true
```

`oci://us-west1-docker.pkg.dev/haarchri/xxx/\" is not a valid chart repository or cannot be reached: object required"}`

### PR DESCRIPTION
**Pull request by ChristofferNissen**
Add support for OCI based Helm Chart registries

```yaml
...
charts:
- name: argo-cd
  plainHTTP: true
  repo:
    url: oci://localhost:5000/charts/
...
```

Closes #40

### CODE REVIEW

File: pkg/helm/chart.go [hunk 1]
```diff
@@ -149,6 +152,42 @@ func (c Chart) ResolveVersion() (string, error) {
 func (c Chart) LatestVersion() (string, error) {
 	config := cli.New()
 
+	if strings.HasPrefix(c.Repo.URL, "oci://") {
+
+		ref := strings.TrimPrefix(strings.TrimSuffix(c.Repo.URL, "/")+"/"+c.Name, "oci://")
+
+		repo, err := remote.NewRepository(ref)
```
Comment (ChristofferNissen) [inline pkg/helm/chart.go:159]: Setup auth

**Comment by haarchri** [comment]
awesome

**Comment by ChristofferNissen** [comment]
Let me know if it works for you :pray:
